### ISSUE TITLE
Error: Querying / filtering on e-mail address fails

### ISSUE THREAD

**Issue by paulflakstad** [npolar/icelastic#35]
Field-querying (`q-<field>=<value>`) and field-filtering (`filter-<field>=<value>`) using an e-mail address as the value produces unexpected results.

Field-querying produces 203 results:
http://api.npolar.no/person/?format=json&facets=false&q-email=nalan.koc%40npolar.no

Field-filtering produces 0 results:
http://api.npolar.no/person/?q=&format=json&facets=false&filter-email=nalan.koc%40npolar.no

**Comment by cnrdh** [comment]
The problem was ES miksconfiguration (tokenizing emails)
